version: '3.8'

services:
  server:
    image: server
    build: ./server
    command: /bin/sh entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /client/app/node_modules
    networks:
      - 3state-app
  client:
    image: client
    build: ./client
    ports:
      - 3001:3001
    volumes:
      - ./client:/app
      - /client/app/node_modules
    networks:
      - 3state-app
networks:
  3state-app:
    driver: bridge